#!/usr/bin/env bash
# displays Holberton School 10 times.

C=1
while [ $C -lt 11 ]
do
    if [ $C = 4 ]
    then
        echo "bad luck"
    elif [ $C = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let C+=1
done