#!/usr/bin/env bash
# displays information about the holbertonschool file.

F="holbertonschool"

if [ -e "$F" ]
then
    echo "holbertonschool file exists"
    if [ ! -s "$F" ]
    then
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if [ -f "$F" ]
    then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi